<script>
</script>

<section class="statement">
	<p class="bold">Terms of Use</p>

	<p>
		This document is an electronic record in terms of Information Technology Act, 2000, amendments
		thereof from time to time and the rules thereunder as applicable and the amended provisions
		pertaining to electronic records in various statutes as amended by the Information Technology
		Act, 2000. This electronic record is generated by a computer system and does not require any
		physical or digital signatures. Please read the terms of use carefully before registering,
		accessing or using the Gullak Money Services (defined below). The terms and conditions are a
		legal contract (&quot;Agreement&quot;) between You and Finterscale Technology Private Limited
		(&ldquo;Gullak Money/ Gullak /Company&rdquo;) having its registered office at 4th Floor,
		Building, 387, Koramangala 4th Block, Koramangala, Bengaluru, Karnataka 560034, India. You agree
		and acknowledge that you have read the terms and conditions set forth below. If you do not agree
		to these terms and conditions or do not wish to be bound by these terms and conditions, you may
		not use the Services and/or immediately terminate the Services and/or uninstall the mobile
		application. We may amend the terms and conditions at any time by posting an updated version at
		the website and Mobile App (App/Platform). The updated version of the Terms of Service shall
		take effect immediately upon posting. Your continued use of the App following the posting of
		changes will mean that You accept and agree to the revisions including additional Terms or
		removal of portions of these Terms, modifications etc.
	</p>

	<p>
		Definition &ldquo;We&rdquo;, &ldquo;Us&rdquo;, &ldquo;Our&rdquo; - shall refer to Finterscale
		Technology Private Limited&ldquo;You&rdquo;, &ldquo;Yours&rdquo;, &ldquo;Yourself&rdquo;,
		&ldquo;User&rdquo;- refers to any non-registered individual or corporate body, registered user
		of the App,including but not limited to users of services provided by Gullak &ldquo;Gullak
		App&rdquo; - The mobile application(s), hosted by Gullak Money and for providing Gullak services
		to its users, including its business partners and service providers and also includes any and
		all Services where it acts as an Intermediary . &ldquo;Gullak Services&rdquo; - shall include
		all services extended but not limited to purchase/investment of Gold and other similar
		investment line. &ldquo;Business Partners&rdquo; &ndash; Shall refer to any individual, group of
		individuals defined under law with whom Gullak have a contractual relationship and not limited
		to Clients, Advertisers, Financial institutions
	</p>

	<p class="bold">Eligibility</p>

	<p>By accessing the Service and Gullak App You represent that:-</p>

	<p>
		1) You are 18 years of age or older 2) You are capable of entering into a contract /legally
		binding agreement 3) You have the right, authority and capability to enter into this Agreement
		abiding by all the provisions of the &ldquo;terms of use&rdquo; 4) You are not impersonating any
		person or entity, or falsely stating your age or affiliation with any person or entity. Gullak
		shall reserve the right to terminate your contract to use in case of any incorrect
		representation of the above-mentioned conditions. 5) The mandatory information and Officially
		valid document(s) &ldquo;OVD&rdquo;/ document details mentioned by you are true &amp; correct
		and belong to You. 6) We will at all times assume (and by using this App you warrant that) you
		have the legal ability to purchase and sell Gold and otherwise use this Platform, and are
		capable of being bound by these Terms and Conditions. 7) Further, by using the App, You confirm
		that you are not registered under any applicable Goods and Services Tax Act, 2017 and that if,
		in the course of your relationship with our App and/or one of our Business Partner, you become
		registered under the applicable Goods and Services Tax Act, 2017, you shall inform our business
		partner of your change in status immediately. 8) If necessary, you shall seek independent tax
		advice, and these Terms and Conditions do not constitute any tax advice to You.
	</p>

	<p class="bold">Registration</p>

	<p>
		In order to use the Services You need to register on the Gullak App/Platform and provide us with
		accurate and complete information as required. You are also required to keep your accounts, KYC
		details and contact information complete and updated at all times.
	</p>

	<p>
		Once you sign-up on App you are entitled to a Gullak Account. Once registered, certain services
		may ask you for additional information in order or avail such service and may involve creation
		of sub-accounts for availing such services.
	</p>

	<p class="bold">Gullak Services</p>

	<p>
		Gullak Account An account that you create when you sign-up/register with Gullak to access the
		Services, including the following:
	</p>

	<p>
		1) This account allows you to access the App, browse through the Service, make payment using
		UPI, debit card, credit cards or net banking collectively known as (&lsquo;Payment Gateway
		Services&rsquo;) as permissible for the investment purchase of Gold 2) The Company may also ask
		You to provide certain additional information about yourself on a case-to-case basis. 3) Access
		to Gullak Account enables you to browse through Gullak Services provided by Gullak and in order
		to avail, enroll or use any such Service you may need to additionally register for such services
		by providing some more information as required under the Terms of Use of such products/services.
		4) Allows you to share and maintain the Know Your Customer &ldquo;KYC&rdquo; details and
		information for underwriting purposes for other financial and non-financial products available
		on the App 5) You further agree to the Privacy Policy as applicable for Finterscale Entity. In
		order to avail the Services, you need a mobile, internet or any other supported device that
		meets the compatibility requirements of accessing the app and the website, which may change from
		time to time. 6) You are allowed to purchase Gold pursuant to the collaboration between the
		Company and Augmont Gold. 7) The Company hereby grants You, a limited, non-exclusive,
		non-transferable, royalty free license to use the App/Platform for the purposes of availing the
		Services. 8) The services offered on the Platform shall include, but is not limited to the
		following: (a) facilitating buying and selling of Gold; and (b) maintaining a record of Your
		personal information and financial transactions in a secure and confidential manner;.
		(&ldquo;Platform Services&rdquo;). 9) However, before placing the order and availing the
		Services, the User may be required to provide certain KYC documentation and other information as
		may be required by the Business Partner( Currently Augmont, the same shall be updated from time
		to time) in such form and manner as it may deem fit. 10) This information may be requested from
		You at the time of registration, or at a later stage, including the following events, to prevent
		fraudulent activities: You withdraw your purchase of Gold; and/or wish to get Your Customer Gold
		delivered to Your doorstep. 11) The KYC verification shall be undertaken based on the PAN Card
		issued to You. You shall upload a clear picture of your PAN Card except in cases where e-PAN is
		provided by You. 12) We shall verify Your details from the database of the issuing authority,
		including through Digilocker. 13) If You do not have a PAN Card, you may submit Form 60 to Us.
		It is hereby clarified that any Services offered (purchase, sale or transfer of Gold on
		Augmont&rsquo;s platform) are governed under specific terms and conditions of Augmont, operated
		and managed by Gold India Private Limited which can be accessed at
		https://www.augmont.com/terms-conditions 14) The Purchase only Digital Gold to start with on a
		pre-payment basis, with an applicability of 3% GST on all purchases. No KYC is required for
		purchase upto 29.999 gms of gold. The gold once purchased cannot be sold before 48 hours of
		purchase. 15) It is also clarified that the Company is merely providing a platform to its Users
		to facilitate the transaction of sale and investment of Gold and will not be liable in any
		manner with respect to the products and/or services offered to You by the respective Business
		Partners 16) You hereby agree and acknowledge that the data and information provided on the App
		does not constitute advice of any nature whatsoever and shall not be relied upon by You while
		making investment decisions and You shall be solely responsible for any investment decisions and
		for the purchase of any Gold on the App. 17) In no event shall the Company be liable to You for
		any loss or damage that may cause or arise from or in relation to these Terms of Use and/or due
		to use of this App/Platform or due to investments made using this App/Platform. 18) Use of the
		App/Platform and availing the Services: You acknowledge that the Services are for Your personal
		use and agree not to publish the Gold prices or descriptions of Gold and/or any other
		information displayed on the Platform (in lieu of Your access to the App/Platform) on any other
		medium. 19) You agree that You shall not copy, reproduce, sell, redistribute, publish, enter
		into a database, display, perform, modify, alter, transmit, license, create derivatives from,
		transfer or in any way exploit any part of any information, content, materials, services
		available from or through the App/Platform, except that You may download the App for Your own
		personal, internal and non-commercial use. 20) You agree that You will not use the App/Platform
		in any manner or engage in any activity that may damage, disable or impair or adversely affect
		the use of the Platform or interfere with any other users&rsquo; use, legal rights, or enjoyment
		of the Platform. Further, You agree not to remove any text, copyright or other proprietary
		notices contained in the content downloaded from the App/Platform.
	</p>

	<p class="bold">Placing of order</p>

	<p>
		1) You can purchase Gold on the Platform on a pre-payment basis i.e., once you place the order
		and confirm the transaction for purchase of Gold, and agree to the Terms of Use the Platform
		will notify Augmont. 2) Once the payments are received by Augmont and the KYC information (if
		and where applicable) is found acceptable, Augmont shall issue an invoice to You confirming the
		Customer Order placed within a period of 3 (three) business days of placing such order, in a
		manner it may deem fit. 3) Notwithstanding anything to the contrary contained in these Terms and
		Conditions, Company and/or Augmont shall be entitled to accept or reject the User, for any
		reason whatsoever, at its sole and exclusive discretion. The money shall be refunded in case of
		order reject. 4) Once the Customer Order is placed, You are not entitled to cancel such a
		Customer Order, provided however that such Customer Order shall stand cancelled if the payment
		fails for any reason whatsoever. The Platform and/or Augmont reserves the right to cancel the
		Customer Order, at its sole discretion, if Your information, provided prior to placing the
		Customer Order, is not found acceptable and the Platform and/or Augmont are of the opinion that
		You are not eligible to purchase Gold from Augmont. 5) In case of rejection of any of Your
		Customer Order, where payments have been received by Gullak/ Augmont such payments shall be
		returned to You in accordance with these Terms of Use or the terms and conditions of Augmont as
		applicable. 6) The quantity of Gold purchased by You shall be stored with the Custodian in a
		vault on Your behalf. You hereby authorize Augmont to store such physical gold products
		purchased by You pursuant to the Customer Order, including, but not limited to, bullion, coins
		or jewellery (as the case may be) in the secured vault maintained by the Custodian on Your
		behalf (&ldquo;Customer Gold&rdquo;). 7) It is hereby clarified that Your purchase of the
		physical gold corresponding to Your Customer Order shall be deemed to be completed and title in
		relation thereto shall be deemed to have been passed to You upon such relevant portion of the
		Customer Gold being stored in the vault with the Custodian on Your behalf in accordance with the
		terms and conditions of Augmont, subject to applicable laws. 8) You will be provided with
		storage for your Customer Gold perpetually as per Augmont&rsquo;s discretion, or for such period
		as more particularly stipulated by Augmont in this regard from time to time at its sole
		discretion and notified to Customers on the Platform (&ldquo;Free Storage Period&rdquo;). 9)
		Security Trustee: The Custodian has taken the necessary insurance policy/ies, in case of
		occurrence of an event not covered in such insurance policy/ies, the Customer Gold may be at
		risk. The insurance policy/ies obtained by the Custodian are in line with the global industry
		practices and cover losses due to fire, lightning, theft, cyclone, earthquake, flood, etc. but
		do not cover losses due to events such as war, revolution, derelict weapons of war, nuclear
		radiation, etc. In the event of any expenses or charges remaining payable to any Intermediaries
		or otherwise till actual delivery or fulfilment of any of Your Customer Orders for any reason,
		including where Augmont is unable to service such requests for any of its event of default,
		thereby adversely affecting or jeopardizing the fulfilment of Your Customer Orders, the details
		of the same shall be available at Augmont terms and conditions.
	</p>

	<p class="bold">Pricing and Payment policy</p>

	<p>
		1) Except where noted otherwise, the price displayed on the App/Platform, represents the market
		linked price of Gold as indicated by Augmont. 2) Market linked prices means that these quotes
		are linked to the prices of gold in the commercial bullion market in India. However, it does not
		indicate that the gold prices displayed on the Platform will always be the same as that of the
		prevalent prices displayed in other commercial bullion markets. As a purchaser, it is your
		responsibility to compare the prices and take appropriate decisions after adequate diligence.
		Notwithstanding the foregoing, you understand that these prices may vary multiple times within a
		day, and accordingly 3) Your payment obligations for any Customer Order will depend on the
		prices displayed at the relevant time. 4) Payment policy: Payment will be accepted through the
		payment options made available on the App/ Platform, which may include redirection to a payment
		gateways and aggregators hosted by third-party websites or UPI applications. 5) At the time of
		purchase, fulfilment sale and/or transfer of Gold, the relevant taxes will be chargeable as
		applicable as per the Government regulations. However, please note that the detailed payment
		terms, delivery, warranty and cancellation and refund policy and other payment policy are
		subject to the terms and conditions of Augmont which can be accessed at
		https://www.augmont.com/terms-conditions
	</p>

	<p class="bold">Delivery of Gold</p>

	<p>
		1) For the purposes of making delivery to You, You are required to provide a valid address
		and/or any other documents/information/ biometric identification that may be specified in this
		regard by Company and Augmont on the Platform from time to time. 2) You are required to take
		delivery of Your Customer Gold within such maximum period as shall be specified for this purpose
		by Augmont from time to time on the Platform In the event that no valid address has been
		provided by You during the maximum storage period, then Platform and/ Augmont shall for a period
		1 (one) year commencing from the date of expiry of maximum storage period at its sole discretion
		attempt at least once to contact You using the contact information provided by You to obtain
		either (i) an address to which You would require the gold in question to be delivered or (ii)
		Your bank account details into which sale proceeds of the Gold shall be deposited. 3) In the
		event that Platform and/or Augmont has not been able to contact You during the additional period
		using the contact information provided by You, Augmont shall be entitled to purchase such
		Customer Gold with the purchase price being the applicable prevailing price displayed on the
		Platform for purchase of Gold from Customers as per details detailed in Augmont Terms and
		conditions.
	</p>

	<p>
		Return, Refund and Cancellation Policy 1) On use of any coupon or discounts, as made available
		by us on the Platform or any other website or platform of any authorised third party, for
		purchase of Gold, the same shall be verified and adjusted, as may be necessary, within 7 (seven)
		days of use of such coupon or discount. 2) There is no minimum lock-in period for the
		investment. 3) Once the payment has been confirmed, the same shall be binding on You and cannot
		be cancelled. 4) You can opt out of auto investing on the Platform by undertaking the following
		actions: a) To pause &#8195; (i) You'll find the pause button on the home screen under your
		savings. &#8195;(ii) You can choose the duration you wish to pause for. b) To delete &#8195; (i)
		Go into profile section. &#8195;&#8195; Select autopay. &#8195;&#8195; Select the mandate
		&#8195;&#8195; Delete. &#8195;(ii) You can also delete the mandate via your UPI app
	</p>

	<p class="bold">Intellectual Property Rights</p>

	<p>
		Intellectual Property Rights for the purpose of this Terms of Use shall always mean and include
		copyrights whether registered or not, patents including rights of filing patents, trademarks,
		trade names, trade dresses, house marks, collective marks, associate marks and the right to
		register them, designs both industrial and layout, geographical indicators, moral rights,
		broadcasting rights, displaying rights, distribution rights, selling rights, abridged rights,
		translating rights, reproducing rights, performing rights, communicating rights, adapting
		rights, circulating rights, protected rights, joint rights, reciprocating rights, infringement
		rights. All those Intellectual Property rights arising as a result of domain names, internet or
		any other right available under applicable law shall vest in the domain of Gullak Money or
		Finterscale entities as the owner of such domain name. The Parties hereto agree and confirm that
		no part of any Intellectual Property rights mentioned hereinabove is transferred in the name of
		User and any intellectual property rights arising as a result of these presents shall also be in
		the absolute ownership, possession and Our control or control of its licensors, as the case may
		be.
	</p>

	<p>
		All material on this Gullak money website and mobile application, including images,
		illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other
		intellectual property rights of Finterscale Technologies Pvt Ltd. Material on Website is solely
		for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post,
		transmit or distribute such material in any way, including by email or other electronic means
		and whether directly or indirectly and You must not assist any other person to do so. Without
		the prior written consent of the owner, modification of the materials, use of the materials on
		any other platform or networked computer environment or use of the materials for any purpose
		other than personal, non-commercial use is a violation of the copyrights, trademarks and other
		proprietary rights, and is prohibited.
	</p>

	<p class="bold">Termination</p>

	<p>
		You agree that Gullak at its sole discretion may terminate your contract without prior notice
		and restrict your access to the App/Platform if determined that You have violated the terms of
		use and You consent that in case Gullak suffers losses, not limited to monetary losses, due to
		Your actions, We can take injunctive relief or any other legal action as deemed necessary within
		the said circumstances and Gullak is not liable for any loss to You due to termination.
	</p>

	<p class="bold">Limitation of Liability</p>

	<p>
		Financial and non-financial transactions performed by You on the Platform is always processed by
		You or under Your exclusive authorization.
	</p>

	<p>
		In no event will Gullak be liable for any indirect, consequential, incidental, special or
		punitive damages, including without limitation damages for loss of profits or revenues, business
		interruption, loss of business opportunities, loss of data or loss of other economic interests,
		whether in contract, negligence, tort or otherwise, arising from the use of or inability to use
		the Services, however caused and whether arising in contract, tort, negligence, warranty or
		otherwise.
	</p>

	<p class="bold">Indemnification</p>

	<p>
		You shall indemnify and hold harmless Gullak Money its owner, licensee, affiliates,
		subsidiaries, group companies (as applicable) and their respective officers, directors, agents,
		and employees, from any claim or demand, or actions including reasonable attorneys' fees, made
		by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use,
		privacy Policy and other Policies, or Your violation of any law, rules or regulations or the
		rights (including infringement of intellectual property rights) of a third party.
	</p>

	<p />

	<p class="bold">Force Majeure</p>

	<p>
		A Force Majeure Event shall mean any event that is beyond the reasonable control of Gullak Money
		and shall include but not limited to war, riots, fire, flood, acts of God, explosion, strikes,
		lockouts, slowdowns, prolonged shortage of energy supplies, Pandemic, computer hacking,
		unauthorized access to computer data and storage devices, computer crashes ,acts of state,
		governmental, legal or regulatory actions prohibiting or impeding Gullak Money from performing
		its respective obligations under the contract.
	</p>

	<p />

	<p class="bold">Dispute, Governing Law &amp; Jurisdiction</p>

	<p>
		This Agreement and the rights and obligations thereunder and the relations of the parties and
		all matters arising under or in connection with this Terms of Use, including the construction,
		validity, performance or termination thereunder, shall be governed by and construed in
		accordance with the laws of the Republic of India. Subject to and without prejudice to the
		amicable settlement, the courts in Bengaluru, Karnataka shall have exclusive jurisdiction to try
		and adjudicate all matters arising in connection with your use of the Services or other matters
		covered herein.
	</p>

	<p />

	<p class="bold">Disclaimers</p>

	<p>
		As part of this continual innovation and improvement, we sometimes may add or remove features
		and functionalities, increase, or decrease limits to our Services, start offering new services
		or stop offering old ones on our Platform. Such offering can also be due to discontinuation of
		any service or offering on the Platform by third party service providers or business partners.
	</p>

	<p>
		We may record or monitor Our conventions with You for records and monitoring quality of our
		conversations.
	</p>

	<p>
		Any content downloaded or otherwise obtained through the use of our Platform is done at your own
		discretion and risk, and We cannot confirm that such documents or contents are error or virus
		free and You understand and acknowledge that you are solely responsible for any damage to your
		devices, for any loss of data that may result from the download of such contents.
	</p>

	<p>
		Gullak and third-party partners make no warranty, express or implied regarding the quality of
		Services including but not limited to:
	</p>

	<p>
		1) the Services will meet your requirements 2) the Services will be uninterrupted, timely or
		error free; or 3) any products, information or material obtained by You in connection with the
		services will meet Your requirements. Except as expressly provided herein and to the full extent
		permitted by law, the Services are provided &quot;as is &quot;, &quot;as available &quot; and
		&quot;with all faults &quot;. All such warranties, representations, conditions, undertakings and
		terms, whether express or implied, are hereby excluded. It is Your responsibility to evaluate
		the accuracy, completeness and usefulness of the Services and other information provided by
		Gullak or generally available. We do not authorize anyone to make any warranty on our behalf and
		You should not rely on any such statement.
	</p>

	<p>
		If you have a dispute with other parties, you release Gullak (and our affiliates and officers,
		directors, agents, and employees thereof) from claims, demands and damages (actual and
		consequential) of every kind and nature, known and unknown, arising out of or in any way
		connected with such disputes.
	</p>

	<p class="bold">Contact Us</p>

	<p>
		Finterscale Technology Private Limited 4th Floor, Building, 387, Koramangala 4th Block,
		Koramangala, Bengaluru, Karnataka 560034
	</p>

	<p>Tel: +91 - 80486 41973 Email: support@gullak.money</p>
</section>

<style lang="sass">
	.statement {
		padding: 10%;
	}

	.statement .bold {
		font-weight: bold;
	}
</style>
